let courses__data = [
  {
    id: 1,
    title: "Ing-tili",
    standard: "Standard",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 2,
    standard: "Standard",
    title: "Rus-tili",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 3,
    standard: "Standard",
    title: "Nemis-tili",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 4,
    standard: "Standard",
    title: "Arab-tili",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 5,
    standard: "Standard",
    title: "Fransuz-tili",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 6,
    standard: "Standard",
    title: "Koreys-tili",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 7,
    standard: "Standard",
    title: "Xitoy-tili",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 8,
    standard: "Standard",
    title: "Yapon-tili",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 9,
    standard: "Standard",
    title: "Turk-tili",
    category: "Tillar",
    des: `Standard 1 is a foundation Standard that reflects 7 important concepts...`,
  },
  {
    id: 10,
    standard: "Standard",
    title: "Front-End",
    category: "Dasturlash",
    des: `Standard 2 builds on the foundations of Standard 1 and includes requirements...`,
  },
  {
    id: 11,
    standard: "Standard",
    title: "Back-End",
    category: "Dasturlash",
    des: `Standard 2 builds on the foundations of Standard 1 and includes requirements...`,
  },
  {
    id: 12,
    standard: "Standard",
    title: "3D Max",
    category: "Dasturlash",
    des: `Standard 2 builds on the foundations of Standard 1 and includes requirements...`,
  },
  {
    id: 13,
    standard: "Standard",
    title: "Roboto-texnika",
    category: "Dasturlash",
    des: `Standard 2 builds on the foundations of Standard 1 and includes requirements...`,
  },
  {
    id: 14,
    standard: "Standard",
    title: "Mobil-dasturlash",
    category: "Dasturlash",
    des: `Standard 2 builds on the foundations of Standard 1 and includes requirements...`,
  },
  {
    id: 15,
    standard: "Standard",
    title: "Suniy Intelekt",
    category: "Dasturlash",
    des: `Standard 2 builds on the foundations of Standard 1 and includes requirements...`,
  },
  {
    id: 16,
    standard: "Standard",
    title: "Matematika",
    category: "Aniq Fanlar",
    des: `Standard 3 of the Aged Care Quality Standards applies to all services delivering personal...`,
  },
  {
    id: 17,
    standard: "Standard",
    title: "Geometriya",
    category: "Aniq Fanlar",
    des: `Standard 3 of the Aged Care Quality Standards applies to all services delivering personal...`,
  },
  {
    id: 18,
    standard: "Standard",
    title: "Fizika",
    category: "Aniq Fanlar",
    des: `Standard 3 of the Aged Care Quality Standards applies to all services delivering personal...`,
  },
  {
    id: 19,
    standard: "Standard",
    title: "Algebra",
    category: "Aniq Fanlar",
    des: `Standard 3 of the Aged Care Quality Standards applies to all services delivering personal...`,
  },
  {
    id: 20,
    standard: "Standard",
    title: "Biologiya",
    category: "Tabiiy Fanlar",
    des: `Standard 4 of the Aged Care Quality Standards focuses on services and supports...`,
  },
  {
    id: 21,
    standard: "Standard",
    title: "Adabiyot",
    category: "Tabiiy Fanlar",
    des: `Standard 4 of the Aged Care Quality Standards focuses on services and supports...`,
  },
  {
    id: 22,
    standard: "Standard",
    title: "Ona-tili",
    category: "Tabiiy Fanlar",
    des: `Standard 4 of the Aged Care Quality Standards focuses on services and supports...`,
  },
  {
    id: 23,
    standard: "Standard",
    title: "Tarix",
    category: "Tabiiy Fanlar",
    des: `Standard 4 of the Aged Care Quality Standards focuses on services and supports...`,
  },
  {
    id: 24,
    standard: "Standard",
    title: "Kimyo",
    category: "Tabiiy Fanlar",
    des: `Standard 4 of the Aged Care Quality Standards focuses on services and supports...`,
  },
  {
    id: 25,
    standard: "Standard",
    title: "Jismoniy",
    category: "Tabiiy Fanlar",
    des: `Standard 4 of the Aged Care Quality Standards focuses on services and supports...`,
  },
  {
    id: 26,
    standard: "Standard",
    title: "Tikish",
    category: "Mexnat",
    des: `Standard 5 Learning Resources. Learning Resources ensure that the school has the...`,
  },
  {
    id: 27,
    standard: "Standard",
    title: "Bichish",
    category: "Mexnat",
    des: `Standard 5 Learning Resources. Learning Resources ensure that the school has the...`,
  },
  {
    id: 28,
    standard: "Standard",
    title: "To'qish",
    category: "Mexnat",
    des: `Standard 5 Learning Resources. Learning Resources ensure that the school has the...`,
  },
];
export default courses__data;
